steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:0.13.3'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd cloudrun-app
      terraform init
  - id: 'tf apply'
    name: 'hashicorp/terraform:0.13.3'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd cloudrun-app
      terraform apply -auto-approve
